/*     Copyright 2009 Graeme Roberts ::
        prettychips is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    prettychips is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with prettychips.  If not, see <http://www.gnu.org/licenses/>.
*/

// includes
#include "nds/fifomessages.h"
#include <math.h>
#include <nds.h>
#include <stdio.h>

// My headers.
#include "extras.h"
#include "menus.h"
#include "mytimers.h"
#include "topscreen.h"

int wovalate;
u8 nVolume;
int bg3;
int bg3sub;
int bpm;
int curkey;
bool fTri;
bool wOval;
int wovalate;
int ftriangulate;
int hpm;
int lpm;
u8 nPan;
int octave;
float pitching;
int scale;
int volbent;
int wCycle;
float whammy;

// Include the font header generated by grit
//#include "font.h"
//---------------------------------------------------------------------------------
int main(void) {
  //---------------------------------------------------------------------------------

  const int tile_base = 0;
  const int map_base = 20;

  // state the global starting values

  wOval = false;
  fTri = false;
  wovalate = 1;
  ftriangulate = 0;

  curkey = 0;
  octave = 1;
  scale = 0;
  chrootnote();

  pitching = 0;
  volbent = 0;

  wCycle = 0;
  nVolume = 127;
  nPan = 64;
  bpm = 120;
  hpm = bpm / 60;
  lpm = hpm;
  effect();

  touchPosition touch;
  int tx, ty;

  soundEnable();
  lcdMainOnBottom();
  consoleDemoInit(); // setting the sub screen for printing, in case I implement
                     // a debug mode.
  videoSetMode(MODE_5_2D);

  vramSetBankA(VRAM_A_MAIN_BG_0x06000000);
  bg3 = bgInit(3, BgType_Bmp8, BgSize_B8_256x256, 0, 0);

  videoSetModeSub(MODE_5_2D);
  vramSetBankB(VRAM_B_MAIN_BG_0x06000000);
  bg3sub = bgInitSub(3, BgType_Bmp16, BgSize_B16_256x256, 0, 0);
  decompress(topscreenBitmap, BG_GFX_SUB, LZ77Vram);

  vramSetBankC(VRAM_C_SUB_BG);
  PrintConsole *console =
      consoleInit(0, 2, BgType_ExRotation, BgSize_ER_256x256, map_base,
                  tile_base, false, false);

  int bg2 = console->bgId;

  unsigned int angle = 0;
  int scrollX = 0;
  int scrollY = 0;
  int scaleX = intToFixed(1, 8);
  int scaleY = intToFixed(1, 8);

  setMenuUP();
  theBeat();

  makeMeSomeButtons();

  // Initial keys launch.
  makeNotes();
  doKeys();
  noteHeld[0] = false;

  while (1) { // main loop

    scanKeys();

    touchRead(&touch);
    tx = touch.px;
    ty = touch.py;

    /*
     *  TOUCH ME
     */

    if (keysDown() & KEY_DOWN)
      touchMe(0);
    if (keysDown() & KEY_LEFT)
      touchMe(1);
    if (keysDown() & KEY_UP)
      touchMe(2);
    if (keysDown() & KEY_RIGHT)
      touchMe(3);
    if (keysDown() & KEY_Y)
      touchMe(4);
    if (keysDown() & KEY_X)
      touchMe(5);
    if (keysDown() & KEY_A)
      touchMe(6);
    if (keysDown() & KEY_B)
      touchMe(7);

    /*
     *  HOLD ME
     */

    if (keysHeld() & KEY_DOWN)
      holdMe(0);
    if (keysHeld() & KEY_LEFT)
      holdMe(1);
    if (keysHeld() & KEY_UP)
      holdMe(2);
    if (keysHeld() & KEY_RIGHT)
      holdMe(3);
    if (keysHeld() & KEY_Y)
      holdMe(4);
    if (keysHeld() & KEY_X)
      holdMe(5);
    if (keysHeld() & KEY_A)
      holdMe(6);
    if (keysHeld() & KEY_B)
      holdMe(7);

    /*
     *  KILL ME
     */
    if (!(keysHeld() & KEY_L)) {
      if (keysUp() & KEY_DOWN)
	killMe(0);
      if (keysUp() & KEY_LEFT)
	killMe(1);
      if (keysUp() & KEY_UP)
	killMe(2);
      if (keysUp() & KEY_RIGHT)
	killMe(3);
      if (keysUp() & KEY_Y)
	killMe(4);
      if (keysUp() & KEY_X)
	killMe(5);
      if (keysUp() & KEY_A)
	killMe(6);
      if (keysUp() & KEY_B)
	killMe(7);
    }
    if ((keysHeld() & KEY_L)) {
      if (keysUp() & KEY_DOWN)
	LMe(1);
      if (keysUp() & KEY_LEFT)
	LMe(1);
      if (keysUp() & KEY_UP)
	LMe(2);
      if (keysUp() & KEY_RIGHT)
	LMe(3);
      if (keysUp() & KEY_Y)
	LMe(4);
      if (keysUp() & KEY_X)
	LMe(5);
      if (keysUp() & KEY_A)
	LMe(6);
      if (keysUp() & KEY_B)
	LMe(7);
    }

    /* L + R are panic buttons ;__; */

    if (keysDown() & KEY_R)
      PANIC();

    /* sends touch data for button checking over on menus.c */

    if (keysHeld() & KEY_TOUCH)
      isWeHasButton(tx, ty);

    if (keysDown() & KEY_TOUCH)
      keysDownOnly(tx, ty);

    if (keysUp() & KEY_TOUCH)
      whammy = 0;

    if (keysHeld() & KEY_SELECT) {
      if (bpm > 30) {
	if (keysDown() & KEY_DOWN)
	  bpm -= 1;
	if (keysHeld() & KEY_LEFT)
	  bpm -= 1;
      }
      if (keysDown() & KEY_UP)
	bpm += 1;
      if (keysHeld() & KEY_RIGHT)
	bpm += 1;

      if (keysHeld() & KEY_START) {
      }
    }

    /* updates the bpm every fram, for future use, dollface. */
    hpm = bpm / 60;
    iprintf("\x1b[0;0H%i", bpm);
    bgSetRotateScale(bg2, angle, scaleX, scaleY);
    bgSetScroll(bg2, scrollX, scrollY);
    bgUpdate();
    swiWaitForVBlank();
  }

  return 0;
}
