/*     Copyright 2009 Graeme Roberts ::
        prettychips is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    prettychips is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with prettychips.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "nds/fifomessages.h"
#include <math.h>
#include <nds.h>
#include <stdio.h>

#include "extras.h"
#include "menus.h"
#include "mytimers.h"
#include "topscreen256.h"

int wovalate;
u8 nVolume;
int bg3;
int bg3sub;
int bpm;
int curkey;
bool fTri;
bool wOval;
int wovalate;
int ftriangulate;
int hpm;
int lpm;
u8 nPan;
int octave;
float pitching;
int volbent;
int wCycle;
float whammy;

// Include the font header generated by grit
//#include "font.h"
//---------------------------------------------------------------------------------
int main(void) {
  //---------------------------------------------------------------------------------

  // state the global starting values

  wOval = false;
  fTri = false;
  wovalate = 1;
  ftriangulate = 0;

  curkey = 0;
  octave = 1;
  chrootnote();

  pitching = 0;
  volbent = 0;

  wCycle = 0;
  nVolume = 127;
  nPan = 64;
  bpm = 120;
  hpm = bpm / 60;
  lpm = hpm;
  effect();

  touchPosition touch;
  int tx, ty;

  soundEnable();
  videoSetMode(MODE_5_2D);
  vramSetBankA(VRAM_A_MAIN_BG_0x06000000);
  lcdMainOnBottom();
  consoleDemoInit();
  iprintf("yongus");

  bg3 = bgInit(3, BgType_Bmp8, BgSize_B8_256x256, 0, 0);

  // PrintConsole *console =
  //     consoleInit(0, 2, BgType_ExRotation, BgSize_ER_256x256, map_base,
  //                 tile_base, false, false);

  // int bg2 = console->bgId;

  setMenuUP();
  theBeat();

  makeMeSomeButtons();

  // Initial keys launch.
  makeNotes();
  doKeys();
  noteHeld[0] = false;

  while (1) { // main loop

    scanKeys();

    touchRead(&touch);
    tx = touch.px;
    ty = touch.py;

    /*
     *  TOUCH ME
     */

    if (keysDown() & KEY_DOWN) {
      touch_me(0);
    }
    if (keysDown() & KEY_LEFT) {
      touch_me(1);
    }
    if (keysDown() & KEY_UP) {
      touch_me(2);
    }
    if (keysDown() & KEY_RIGHT) {
      touch_me(3);
    }
    if (keysDown() & KEY_Y) {
      touch_me(4);
    }
    if (keysDown() & KEY_X) {
      touch_me(5);
    }
    if (keysDown() & KEY_A) {
      touch_me(6);
    }
    if (keysDown() & KEY_B) {
      touch_me(7);
    }

    /*
     *  HOLD ME
     */

    if (keysHeld() & KEY_DOWN) {
      hold_me(0);
    }
    if (keysHeld() & KEY_LEFT) {
      hold_me(1);
    }
    if (keysHeld() & KEY_UP) {
      hold_me(2);
    }
    if (keysHeld() & KEY_RIGHT) {
      hold_me(3);
    }
    if (keysHeld() & KEY_Y) {
      hold_me(4);
    }
    if (keysHeld() & KEY_X) {
      hold_me(5);
    }
    if (keysHeld() & KEY_A) {
      hold_me(6);
    }
    if (keysHeld() & KEY_B) {
      hold_me(7);
    }

    /*
     *  RELEASE ME
     */
    if (!(keysHeld() & KEY_L)) {
      if (keysUp() & KEY_DOWN) {
	release_me(0);
      }
      if (keysUp() & KEY_LEFT) {
	release_me(1);
      }
      if (keysUp() & KEY_UP) {
	release_me(2);
      }
      if (keysUp() & KEY_RIGHT) {
	release_me(3);
      }
      if (keysUp() & KEY_Y) {
	release_me(4);
      }
      if (keysUp() & KEY_X) {
	release_me(5);
      }
      if (keysUp() & KEY_A) {
	release_me(6);
      }
      if (keysUp() & KEY_B) {
	release_me(7);
      }
    }
    if ((keysHeld() & KEY_L)) {
      if (keysUp() & KEY_DOWN) {
	drone_me(1);
      }
      if (keysUp() & KEY_LEFT) {
	drone_me(1);
      }
      if (keysUp() & KEY_UP) {
	drone_me(2);
      }
      if (keysUp() & KEY_RIGHT) {
	drone_me(3);
      }
      if (keysUp() & KEY_Y) {
	drone_me(4);
      }
      if (keysUp() & KEY_X) {
	drone_me(5);
      }
      if (keysUp() & KEY_A) {
	drone_me(6);
      }
      if (keysUp() & KEY_B) {
	drone_me(7);
      }
    }

    /* L + R are panic buttons ;__; */

    if (keysDown() & KEY_R)
      PANIC();

    /* sends touch data for button checking over on menus.c */

    if (keysHeld() & KEY_TOUCH)
      isWeHasButton(tx, ty);

    if (keysDown() & KEY_TOUCH)
      keysDownOnly(tx, ty);

    if (keysUp() & KEY_TOUCH)
      whammy = 0;

    if (keysHeld() & KEY_SELECT) {
      if (bpm > 30) {
	if (keysDown() & KEY_DOWN)
	  bpm -= 1;
	if (keysHeld() & KEY_LEFT)
	  bpm -= 1;
      }
      if (keysDown() & KEY_UP)
	bpm += 1;
      if (keysHeld() & KEY_RIGHT)
	bpm += 1;

      if (keysHeld() & KEY_START) {
      }
    }

    /* updates the bpm every fram, for future use, dollface. */
    hpm = bpm / 60;
    // iprintf("\x1b[1;0H%i", bpm);
    // bgSetRotateScale(bg2, angle, scaleX, scaleY);
    // bgSetScroll(bg2, scrollX, scrollY);
    bgUpdate();
    swiWaitForVBlank();

    play_with_everyone();
  }

  return 0;
}
